server:
  port: 8581

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:

      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              #allowCredentials: true
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - OPTIONS
                - DELETE

      routes:
        - id: service_wishlist
          uri: http://localhost:8585
          predicates:
            - Path=/wishlist/**
          filters:
            - AuthenticateFilterFactory


  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: userservice
      


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/
    fetch-registry: true
    register-with-eureka: true
   

  
